### ISSUE TITLE
[1.14.4] Please update to 1.14.4 - 28.1.22

### ISSUE THREAD

**Issue by ProsperCraft** [korti11/bettermuffling#2]
https://github.com/McJtyMods/RFToolsPower/issues/26#issuecomment-535616023

When your mod is included non updated in my pack it causes this crash above.

Better Muffling-1.14.4-0.3.0-Beta

**Comment by ProsperCraft** [comment]
Sorry, wrong target, your mod is fine, it was mousetweaks.

**Comment by korti11** [comment]
No problem. I was just investigating my self and i got it working so I just checked for the versions.
It's also intresting that it was mousetweaks, because my thought was, it was Forbidden & Arcanus, because in your crashlog you used the version 1.1 and it threw an error and I was using the version 1.2 and it worked. But I'm glad you got it working.
